name = "EfficientNets"
uuid = "cb7af4dd-7bed-4342-a916-86f413a32658"
authors = ["Vaclav Macha <vaclav.macha92@gmail.com>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[compat]
Flux = "0.13"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]